if vim.g.loaded_projman then return end
vim.g.loaded_projman = true
local function command(name, fn, opts) vim.api.nvim_create_user_command(name, fn, opts or {}) end
command('ProjManExplore', function(args) require('projman').explore(args.args ~= '' and args.args or nil) end, { nargs = '?' })
command('ProjManExplorerRoot', function() require('projman').explorer_root() end)
command('ProjManExplorerRefresh', function() require('projman').explorer_refresh() end)
command('ProjManFind', function(args) require('projman').find(args.args) end, { nargs = '*' })
command('ProjManNew', function(args) require('projman').create(args.args ~= '' and args.args or nil, args.bang) end, { nargs = '?', bang = true })
command('ProjManProperties', function(args) require('projman').properties(args.args ~= '' and args.args or nil) end, { nargs = '?' })
command('ProjManOpen', function(args) require('projman').open(args.args) end, { nargs = 1 })
command('ProjManSearch', function(args) require('projman').search(args.args) end, { nargs = '*' })
command('ProjManTypes', function() require('projman').types() end)
command('ProjManTypeNew', function() require('projman').type_new(false) end)
command('ProjManRelationTypeNew', function() require('projman').type_new(true) end)
command('ProjManLinks', function() require('projman').links() end)
command('ProjManLink', function(args) require('projman').link(args.args ~= '' and args.args or nil) end, { nargs = '?' })
command('ProjManOutline', function(args) require('projman').outline(args.args ~= '' and args.args or nil) end, { nargs = '?' })
command('ProjManBacklinks', function() require('projman').backlinks() end)
command('ProjManNextField', function() require('projman').jump(1) end)
command('ProjManPreviousField', function() require('projman').jump(-1) end)
command('ProjManRecover', function() require('projman').recover() end)
command('ProjManConflict', function() require('projman').conflict() end)
command('ProjManBack', function() require('projman').back() end)
command('ProjManRetry', function() require('projman').retry() end)
command('ProjManReparent', function(args) require('projman').reparent(args.fargs[1], args.fargs[2]) end, { nargs = '+' })
command('ProjManReorder', function(args) local family = table.remove(args.fargs, 1); require('projman').reorder(family, args.fargs) end, { nargs = '+' })
command('ProjManReconcile', function() require('projman').reconcile() end)
command('ProjManProposals', function() require('projman').proposals() end)
command('ProjManReview', function(args) require('projman').review(args.args) end, { nargs = 1 })
command('ProjManUnstage', function() require('projman').unstage() end)
command('ProjManHealth', function() vim.cmd('checkhealth projman') end)
